export const INITIAL_VISIBLE_JOBS = 30;
export const LOAD_MORE_STEP = 15;

export const CITY_OPTIONS = [
  "Kosovë",
  "Prishtinë",
  "Prizren",
  "Ferizaj",
  "Gjakovë",
  "Gjilan",
  "Podujevë",
  "Vushtrri",
  "Suharekë",
  "Rahovec",
  "Drenas",
  "Lipjan",
  "Malishevë",
  "Kamenicë",
  "Viti",
  "Deçan",
  "Istog",
  "Klinë",
  "Skenderaj",
  "Fushë Kosovë",
  "Kaçanik",
  "Mitrovica Veriore",
  "Shtime",
  "Obiliq",
  "Hani i Elezit",
  "Junik",
  "Dragash",
  "Leposaviq",
  "Graçanicë",
  "Zveçan",
  "Shtërpcë",
  "Artanë",
  "Zubin Potok",
  "Mamusha",
  "Ranillug",
  "Kllokot",
  "Partesh",
  "Krejt Kosovën",
  "Pejë",
  "Mitrovicë",
  "Brezovicë",
  "Xërxë",
  "Mazgit",
  "Çagllavicë",
  "Novobërd",
  "Gjonaj",
  "Shqipëri",
  "Tiranë",
  "Shkodra",
  "Durrës",
  "Lushnje",
  "Sarandë",
  "Të gjitha qytetet",
  "Vlora",
  "Maqedonia e Veriut",
  "Shkup",
  "Austri",
  "Vjena",
  "Grac",
  "Serbi",
  "Presheva",
  "Beograd",
  "Nish",
  "Gjermani",
  "Fulda",
  "Bad Oeynhausen",
  "Frankfurt",
  "Trier",
  "Berlin",
  "Saarland",
  "Bayern",
  "Hannover",
  "Baden-Württemberg",
  "Elz",
  "Stuttgart",
  "Sasbach",
  "Mali i Zi",
  "Ulqin",
  "Tivar",
  "Islanda",
  "Skógar",
  "Kazakistan",
  "Astana",
  "Kroaci",
  "Split",
  "Zvicër",
  "Zürich",
  "Turqi",
  "Bodrum",
  "Antalya",
  "Stamboll",
  "Emiratet e Bashkuara Arabe",
  "Dubai",
  "Hungari",
  "Arabi Saudite",
  "Riyadh",
  "Jeddah",
  "Neom",
  "Slovakia",
  "Bratislava",
  "Bosnja & Hercegovina",
  "Sarajevë",
  "Afrika e Jugut",
  "Zimbabwe",
  "Belgjikë",
  "Irlandë",
  "Libi",
  "Benghazi",
  "Togo",
  "Lome",
  "Gabon",
  "Mongoli",
  "Finland",
  "Kuusamo",
  "Francë",
  "Shtetet e Bashkuara",
  "Çeki"
];

export const JOB_CATEGORY_OPTIONS = [
  "Software",
  "Marketing",
  "Kujdesi Shendetësor",
  "Reklamim dhe Marketing",
  "Agrokulturë",
  "Aviacion",
  "Biznes dhe Menaxhment",
  "Teknologji Informative - ICT",
  "Ndërtimtari",
  "Arsim&Edukim",
  "Energjetikë",
  "Inxhinieri",
  "Argëtim",
  "Fashion",
  "Financa",
  "Gastronomi dhe Hoteleri",
  "Burime Njerëzore",
  "Ligjore",
  "Prodhimtari",
  "Media dhe Lajme",
  "Miniera",
  "OJQ",
  "Të tjera",
  "Farmaceutike",
  "Institucione Publike",
  "Telekomunikim",
  "Transport",
  "Derivate",
  "Paisje Shtëpiake",
  "Ushtarë",
  "Ekonomi",
  "Këshillim",
  "Taksi",
  "Shitje",
  "Dyqan dhe Shitje",
  "Sport",
  "Riciklim",
  "Shperndarje",
  "Sigurim Fizik",
  "Furra",
  "Tregëtim",
  "Kozmetikë dhe Kurim",
  "Tregtimi",
  "Pasuri e Paluajtshme",
  "Organizatë Qeveritare",
  "Qendër Tregtare",
  "Organizatë Jo-Fitimprurëse",
  "Elektronike",
  "Shërbim Printimi",
  "Depo",
  "Shofer",
  "Logjistike",
  "Ftesa për Tender",
  "Përmbarues",
  "Kryeshef Ekzekutiv",
  "Menaxher/e",
  "Administratë",
  "Mirëmbajtje",
  "IT KARRIERA",
  "Kujdesi per Femije",
  "CEO",
  "Laborator",
  "Prokurim",
  "Gjykata Themelore - Pejë",
  "Grante",
  "Qiradhënie/Leasing",
  "Ndërmarrje Publike",
  "Institucionet Qendrore",
  "Arkitekt",
  "Dizajn grafik",
  "Komunë",
  "Bankë",
  "Arkatare",
  "Shërbim",
  "Infermieri",
  "Mjekësi",
  "Praktikë",
  "Saldues",
  "Recepsion",
  "Rrobaqepëse",
  "Dizajn Interieri",
  "Mekanik",
  "Patronist",
  "Kontabilitet",
  "Social Media",
  "Merchandiser",
  "Sigurime",
  "Elektricist",
  "Inspektor",
  "Sektorist",
  "Analist kreditor",
  "Auditor",
  "Teknolog",
  "Gazetari",
  "Ftesë për Ofertë",
  "Retail dhe Distribuim",
  "Siguri & Mbrojtje",
  "Monter",
  "Call Center",
  "Radiologji",
  "Dizajner/e",
  "Serviser",
  "Shkencë",
  "Masazh",
  "Fizioterapi",
  "Remote",
  "Sallon bukurie"
];

export const EXPERIENCE_OPTIONS = [
  "No Experience",
  "1-2 Experience",
  "3-5 Experience",
  "5+ Experience"
];

export const WORK_HOURS_OPTIONS = [
  "Full Time",
  "Part Time",
  "Unordered"
];

export const LANGUAGE_OPTIONS = [
  "Albanian",
  "English",
  "French",
  "German",
  "Serbian",
  "Macedonian",
  "Turkish",
  "Spanish",
  "Arabic",
  "Italian",
  "Swedish"
];

export const REAL_ESTATE_PROPERTY_OPTIONS = [
  "Banesë",
  "Shtëpi",
  "Tokë",
  "Lokal",
  "Zyrë",
  "Truall",
  "Vikendicë",
  "Depo"
];

export const REAL_ESTATE_LISTING_OPTIONS = [
  "Shitje",
  "Qira",
  "Në shitje",
  "Me qira"
];

export const VEHICLE_FUEL_OPTIONS = [
  "Diesel",
  "Benzinë",
  "Hybrid",
  "Elektrik"
];

export const VEHICLE_GEARBOX_OPTIONS = [
  "Manual",
  "Automatik"
];

export const VEHICLE_YEAR_OPTIONS = [
  "2026",
  "2025",
  "2024",
  "2023",
  "2022",
  "2021",
  "2020",
  "2019",
  "2018",
  "2017",
  "2016",
  "2015"
];